<?php

return [
    'logos' => [
        'TechNova',
        'GrowthLab',
        'PixelCraft',
        'Nexus',
        'CodeWave',
        'FinEdge',
        'ScaleFlow',
        'CloudSync',
        'Acme Inc',
        'Stellar Inc',
        'NovaTech',
        'QuantumHR',
    ],
    
    'featured' => [
        'quote' => 'TimeNest reduced manual attendance operations by 82% and saved our HR team over 40 hours every week.',
        'name' => 'Sarah Jenkins',
        'role' => 'VP Operations',
        'company' => 'TechNova',
        'avatar' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80',
        'bg_image' => 'https://images.unsplash.com/photo-1573164713988-8665fc963095?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
        'video_id' => 'L4YCO_HlhGk', // ClickUp / Productivity SaaS review video
        'outcome' => 'Saved 40 hours/week',
    ],

    'videos' => [
        [
            'name' => 'Alex Rivera',
            'role' => 'Engineering Director',
            'company' => 'PixelCraft',
            'quote' => 'Managing shifts across multiple client sites was a logistic nightmare before TimeNest.',
            'video_id' => '_74zrcfV1s0',
            'outcome' => 'Shift planning in minutes',
            'category' => 'Agencies',
            'thumbnail' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        ],
        [
            'name' => 'Chloe Vance',
            'role' => 'Remote HR Manager',
            'company' => 'CloudSync',
            'quote' => 'With teammates in 8 time zones, having automated local-compliant logs has saved our sanity.',
            'video_id' => '3uL2E2w9sWc',
            'outcome' => '98% compliance rating',
            'category' => 'Remote Teams',
            'thumbnail' => 'https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        ],
        [
            'name' => 'Marcus Thorne',
            'role' => 'Co-Founder',
            'company' => 'GrowthLab',
            'quote' => 'We saw operational overhead drop immediately. The setup took less than an hour.',
            'video_id' => '7-45N_xX9v4',
            'outcome' => 'Saved 18 hours/week',
            'category' => 'Startups',
            'thumbnail' => 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        ],
        [
            'name' => 'Liam O\'Connor',
            'role' => 'Head of People',
            'company' => 'ScaleFlow',
            'quote' => 'Our payroll disputes went from daily headaches to zero. The audit trail is solid.',
            'video_id' => 'JtGzLqgI2Y8',
            'outcome' => 'Payroll accuracy 99.7%',
            'category' => 'HR Teams',
            'thumbnail' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        ],
        [
            'name' => 'Elena Rostova',
            'role' => 'Operations VP',
            'company' => 'FinEdge',
            'quote' => 'For enterprise compliance and banking grade security, TimeNest is the gold standard.',
            'video_id' => 'j942wCoE1g8',
            'outcome' => 'Audit ready',
            'category' => 'Enterprises',
            'thumbnail' => 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        ],
        [
            'name' => 'David Chen',
            'role' => 'Independent Consultant',
            'company' => 'Chen Designs',
            'quote' => 'Invoicing and time tracking combined makes billing transparent and lightning-fast.',
            'video_id' => 'dQw4w9WgXcQ',
            'outcome' => '2.4x faster billing',
            'category' => 'Freelancers',
            'thumbnail' => 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        ],
    ],

    'testimonials' => [
        [
            'variant' => 'stats',
            'stats_number' => '40%',
            'stats_label' => 'faster approvals',
            'content' => 'Approving contractor shifts and timesheets used to take up my entire Monday. Now it is literally a single click.',
            'name' => 'Rajesh Patel',
            'role' => 'Engineering Lead',
            'company' => 'CodeWave',
            'categories' => ['Agencies', 'Remote Teams'],
        ],
        [
            'variant' => 'avatar',
            'content' => 'The compliance logs saved us during an external audit. Everything was exported in seconds, with zero gaps. Highly recommended.',
            'name' => 'Sophia Lindqvist',
            'role' => 'Director of Compliance',
            'company' => 'Stellar Inc',
            'avatar' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80',
            'categories' => ['Enterprises', 'HR Teams'],
        ],
        [
            'variant' => 'quote',
            'content' => 'As a remote team with zero physical offices, TimeNest is our virtual lobby. We know who is online, who is working, and compliance is automatic.',
            'name' => 'Oliver Schmidt',
            'role' => 'Co-Founder',
            'company' => 'Nexus',
            'categories' => ['Remote Teams', 'Startups'],
        ],
        [
            'variant' => 'logo',
            'content' => 'We migrated 500+ employees from our legacy ERP time tracking. The transition took 2 days, and our staff adoption rate was 96% in the first week.',
            'name' => 'Aisha Rahman',
            'role' => 'Chief Operations Officer',
            'company' => 'FinEdge',
            'logo' => 'FinEdge',
            'categories' => ['Enterprises', 'HR Teams'],
        ],
        [
            'variant' => 'case_study',
            'content' => 'Our HR department was buried in spreadsheet verification. Implementing TimeNest automated shift checking completely.',
            'name' => 'Karla Jensen',
            'role' => 'VP of HR',
            'company' => 'ScaleFlow',
            'before' => 'manual approvals',
            'after' => 'fully automated workflows',
            'categories' => ['HR Teams', 'Startups'],
        ],
        [
            'variant' => 'avatar',
            'content' => 'Billing hours to multiple clients is no longer a headache. The timesheets auto-export directly to my invoicing software.',
            'name' => 'Nikhil Rao',
            'role' => 'Freelance Developer',
            'company' => 'Independent',
            'avatar' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80',
            'categories' => ['Freelancers'],
        ],
        [
            'variant' => 'stats',
            'stats_number' => '82%',
            'stats_label' => 'HR hours saved',
            'content' => 'TimeNest completely removed the spreadsheet math from our payroll cycles. The calculations are exact and instant.',
            'name' => 'Amanda Brooks',
            'role' => 'Payroll Manager',
            'company' => 'NovaTech',
            'categories' => ['HR Teams', 'Enterprises'],
        ],
        [
            'variant' => 'quote',
            'content' => 'The AI fraud detection flagged buddy-punching patterns we had suspected for months. It paid for itself in the first 30 days.',
            'name' => 'James Carter',
            'role' => 'Operations Manager',
            'company' => 'QuantumHR',
            'categories' => ['Startups', 'Agencies'],
        ],
        [
            'variant' => 'case_study',
            'content' => 'As a digital agency, matching project budgets to developer hours was tedious. TimeNest syncs with our projects dynamically.',
            'name' => 'Linus Torvald',
            'role' => 'Agency Director',
            'company' => 'PixelCraft',
            'before' => 'budget guesswork',
            'after' => 'automated tracking logs',
            'categories' => ['Agencies', 'Freelancers'],
        ],
    ],

    'stats' => [
        [
            'value' => '5000',
            'suffix' => '+',
            'label' => 'Teams Managed',
        ],
        [
            'value' => '1',
            'suffix' => 'M+',
            'label' => 'Hours Tracked',
        ],
        [
            'value' => '98.7',
            'suffix' => '%',
            'label' => 'Customer Satisfaction',
        ],
        [
            'value' => '40',
            'suffix' => '%',
            'label' => 'Average Time Saved',
        ],
    ],

    'case_studies' => [
        [
            'company' => 'TechNova',
            'industry' => 'Cloud Operations & SaaS',
            'team_size' => '250 Employees',
            'results' => [
                'Saved 43 hours/week',
                'Reduced payroll disputes by 92%',
                'Integrated with Slack & Jira',
            ],
            'image' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        ],
        [
            'company' => 'GrowthLab',
            'industry' => 'Global Digital Agency',
            'team_size' => '80 Remote Creators',
            'results' => [
                'Operational overhead reduced by 30%',
                '100% compliant shift logging',
                '24/7 coverage tracking',
            ],
            'image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        ],
        [
            'company' => 'Nexus Devs',
            'industry' => 'Contractor Staffing Network',
            'team_size' => '150 Active Contractors',
            'results' => [
                '24% increase in billable hours',
                'Automated invoicing in 12 currencies',
                'Instant client dashboard reporting',
            ],
            'image' => 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        ],
    ],

    'wall' => [
        ['name' => 'Sophia L.', 'avatar' => 'https://i.pravatar.cc/100?img=32', 'company' => 'Stellar Inc', 'text' => 'Game changer for our payroll compliance.'],
        ['name' => 'Alex R.', 'avatar' => 'https://i.pravatar.cc/100?img=11', 'company' => 'PixelCraft', 'text' => 'Shift planning takes seconds now.'],
        ['name' => 'David C.', 'avatar' => 'https://i.pravatar.cc/100?img=47', 'company' => 'Chen Designs', 'text' => 'Best invoicing tool for contractors.'],
        ['name' => 'Elena R.', 'avatar' => 'https://i.pravatar.cc/100?img=44', 'company' => 'FinEdge', 'text' => 'The onboarding was remarkably simple.'],
        ['name' => 'Marcus T.', 'avatar' => 'https://i.pravatar.cc/100?img=12', 'company' => 'GrowthLab', 'text' => 'We saved over 15 hours in week one.'],
        ['name' => 'Liam O.', 'avatar' => 'https://i.pravatar.cc/100?img=59', 'company' => 'ScaleFlow', 'text' => 'Zero errors in compliance auditing.'],
        ['name' => 'Chloe V.', 'avatar' => 'https://i.pravatar.cc/100?img=49', 'company' => 'CloudSync', 'text' => 'Perfect for remote teams across zones.'],
        ['name' => 'Amanda B.', 'avatar' => 'https://i.pravatar.cc/100?img=22', 'company' => 'NovaTech', 'text' => 'Clean dashboard and very fast reports.'],
        ['name' => 'Rajesh P.', 'avatar' => 'https://i.pravatar.cc/100?img=68', 'company' => 'CodeWave', 'text' => 'One-click approvals are beautiful.'],
    ],
    
    'categories' => [
        'All',
        'Startups',
        'Agencies',
        'Remote Teams',
        'HR Teams',
        'Enterprises',
        'Freelancers',
    ]
];
